trigger:
  - master
  - develop
  - release/*
  - hotfix/*
  - feature/*

pr:
  - master
  - develop
  - releases/*
  - feature/*

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release')]
  isFeature: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature')]
  isHotfix: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

pool:
  vmImage: "ubuntu-16.04"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - bash: echo "Build"
  - stage: Unit_Test
    dependsOn: Build
    jobs:
      - job: JUnit_Test
        steps:
          - bash: echo "JUnit Test"
      - job: Jest_Test
        steps:
          - bash: echo "Jest Test"

  - stage: Integration_Test
    dependsOn: Unit_Test
    condition: and(succeeded(), ne(variables.isHotfix, true), ne(variables.isFeature, true))
    jobs:
      - job: Integration_Test
        steps:
          - bash: echo "JUnit Integration Test"
      - job: UI_Functional_Test
        steps:
          - bash: echo "UI Functional Test"

  - stage: Sonar_Quality_Gate
    dependsOn: Integration_Test
    condition: and(succeeded(), ne(variables.isHotfix, true), ne(variables.isFeature, true))
    jobs:
      - job: Sonar
        steps:
          - bash: echo "Sonarqube analysis"
          - bash: echo "Sonarqube quality gate check"


  - stage: Publish
    dependsOn: Sonar_Quality_Gate
    condition: and(succeeded(), ne(variables.isHotfix, true), ne(variables.isFeature, true))
    jobs:
      - job: Publish_Artifacts
        steps:
          - bash: echo "Publishing"

  - stage: UAT
    condition: and(succeeded(), ne(variables.isHotfix, true), ne(variables.isFeature, true))
    jobs:
      - job: Deploy_UAT
        steps:
          - bash: echo "Provision UAT"
          - bash: echo "Deploy to UAT"

      - job: End2End
        dependsOn: Deploy_UAT
        steps:
        - bash: echo "End2End"
      - job: Performance
        dependsOn: Deploy_UAT
        steps:
          - bash: echo "Performance"

  - stage: Deployment
    dependsOn: UAT
    jobs:
    - job: Deploy_DEV
      condition: and(succeeded(), eq(variables.isDevelop, true))
      steps:
      - bash: echo "Deploy"
    - job: Deploy_Staging
      condition: and(succeeded(), eq(variables.isRelease, true), eq(variables.isMaster, true))
      steps:
        - bash: echo "Deploy"

    - job: Deploy_PROD
      condition: and(succeeded(), eq(variables.isMaster, true))
      steps:
        - bash: echo "Deploy"